name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: off
      GOPROXY: "https://proxy.golang.org"    

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.7

    - name: Build
      env:
        GO111MODULE: off
        GOPROXY: "https://proxy.golang.org"    
      run: go build .

    - name: Test
      run: go test -v
